### ISSUE TITLE
Feature Suggestion: Change color based on a creature type

### ISSUE THREAD

**Issue by Verthiss** [ironmonk88/monks-bloodsplats#1]
Hi! I love the split of the modules! 
It would be great if we could change the default bloodsplat colour based on the creature type ;)

**Comment by BillPitcher** [comment]
On the token in Appearance there is a colour option to set a different bloodspot colour.

**Comment by Verthiss** [comment]
> On the token in Appearance there is a colour option to set a different bloodspot colour.

True! Just not very practical to set it up for each token separately :)

**Comment by ironmonk88** [comment]
Added to the latest release.
