### ISSUE TITLE
[Feature suggestion] Make Bloodsplat toggleable

### ISSUE THREAD

**Issue by stschmitt87** [ironmonk88/monks-bloodsplats#10]
Sometimes my players only want to knockout an enemy, or an NPC might fall unconscious. 

It would be helpful to have a way to manually disable bloodsplat for a specific token, and let it stay visible. Maybe with a macro.

**Comment by BillPitcher** [comment]
(v11) If you remove the Dead effect the bloodspot is removed, but the Token remains invisible and requires 2 clicks on Visibility button in the HUD to make it fully visible.

**Comment by ironmonk88** [comment]
`Unconscious` is now an option for blood splat image.
