### ISSUE TITLE
[Feature Request] Settings Clarification

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#12]
![image](https://user-images.githubusercontent.com/99844555/236119737-c1a29727-7f72-44fd-9e53-a117a342e54f.png)

Since this setting actually adjusts the token opacity and not the bloodsplat opacity, should it maybe get renamed to `Dead Token Opacity` or `Corpse Opacity`?

**Comment by ironmonk88** [comment]
Fixed in the latest release.
