### ISSUE TITLE
Delete animations on token when it becomes bloodsplatted

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-bloodsplats#13]
When a token with animation on it dies, it's annoying to have its animation continue to run, especially since it's not always easy to quickly know which one to delete yourself in the Sequencer effects viewer (for example if the dead token and a live PC happen to both be enfeebled). Would be a nice QoL enhancement to have animations automatically deleted from tokens when they get 'splatted.

This could also be a feature request for Combat Details. Wasn't sure so I just logged it here. :)

**Comment by ironmonk88** [comment]
Added to the latest release.
