### ISSUE TITLE
[BUG] DFred's Convenient Effects causes bloodsplats to revert on world launch

### ISSUE THREAD

**Issue by txm3278** [ironmonk88/monks-bloodsplats#14]
**Describe the bug**
When DFreds Convenient Effects is set to "Replace" mode, bloodsplats revert to tokens on server restart. Mousing over a dead token will then turn the token back into a bloodsplat.

**To Reproduce**
1. Set DFreds Convenient Effects to "replace" mode
2. Set a token to 0 health
3. Token should turn into bloodsplat
4. Close and reopen foundry world
5. Notice dead token is no longer bloodsplat
6. Mouse over token and it will turn back into bloodsplat

**Expected behavior**
Token should remain a bloodsplat when relaunching the world

**Screenshots**
Relaunched world, only moused over top token:
![image](https://github.com/ironmonk88/monks-bloodsplats/assets/25332081/cdd77813-dd06-4cc2-8252-228d8caab17d)

Moused over bottom token:
![image](https://github.com/ironmonk88/monks-bloodsplats/assets/25332081/a112567d-10f6-4bf1-86a5-b4bae6c1662f)

**Please complete as much of the following information as possible:**
 - Chrome, Firefox, and Foundry Client
 - Foundry Version 10.291
 - D&D5e
 - Module version 10.1
 - DFreds Convenient Effects version 4.2.1

**Comment by ironmonk88** [comment]
This may have already been fixed.

**Comment by txm3278** [comment]
I forgot to close this, this was fixed in the initial v11 update. https://ptb.discord.com/channels/862414864692281386/1105866096868868156
