### ISSUE TITLE
[BUG] Token requires 2 clicks on the Visibility button when Dead effect is removed.

### ISSUE THREAD

**Issue by BillPitcher** [ironmonk88/monks-bloodsplats#16]
**Describe the bug**
When removing the Dead effect the bloodspot is removed as expected but the Token remains invisible. Then the first click on the Visibility button sets the Token to the Opacity state, then another click removes the Opacity. 

**To Reproduce**
On a Dead Token, remove the dead effect.

**Expected behavior**
When Removing the Dead effect, to Token should also be fully visible.

**Please complete as much of the following information as possible:**
 - Browser : Chrome and Standalone App
 - Foundry Version v11 (and v10)
 - System D&D5e
 - Module version 11.01
 - Are there any errors in the console [e.g. press F12 and look for red text] No

My players love this module!

**Comment by ironmonk88** [comment]
Fixed in the latest release.
