### ISSUE TITLE
Blood splat showing characters instead of splat on players screen

### ISSUE THREAD

**Issue by MaineKnight** [ironmonk88/monks-bloodsplats#17]
I am using foundry on my windows laptop and using the "extended desktop" feature to show the map on a tv screen for an in person session. When I view the splat on my screen (using foundry app) it looks correct

![Shows_Correct](https://github.com/ironmonk88/monks-bloodsplats/assets/125476146/3d7bc196-b42a-4bf5-813f-50dbc07cc49a)

But on the second screen (the tv) is shows random characters. The characters are always different.

![Shows_Random](https://github.com/ironmonk88/monks-bloodsplats/assets/125476146/f5bbfc45-ff49-4a4e-9ab0-3e8de544802b)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
