### ISSUE TITLE
[BUG] No Module Settings without Libwrapper.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#21]
Bloodsplat's module settings don't appear without Libwrapper active.

### No Libwrapper

![image](https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/7f06fc04-f20d-4ba8-9806-3ebd239170f1)

### Libwrapper

![image](https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/e7bf36ea-6803-4707-a788-dcdca2389dec)

Foundry 11.308
Bloodsplats 11.02
Libwrapper 1.12.13.0

**Comment by ironmonk88** [comment]
Fixed in the latest release.
