### ISSUE TITLE
[BUG] Warning: Asset ID Not Found

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#24]
Shows up the first time a token is marked defeated.

https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/56e26fcb-c3be-4f60-91eb-d057154b9aa5

Foundry 11.308
PF2 4.4.2
Bloodsplats 11.02

**Comment by ironmonk88** [comment]
That's expected.  It's just telling you the image hasn't been loaded before so it's going to go ahead and load it.

**Comment by Crowguard** [comment]
All right.
