### ISSUE TITLE
[BUG] Conflict with Easy Target

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-bloodsplats#27]
Get the attached yellow console warning when loading Bloodsplats (version 11.0.3) with Easy Target.
<img width="544" alt="Screenshot 2023-09-10 at 10 14 19 AM" src="https://github.com/ironmonk88/monks-bloodsplats/assets/90105219/7633bcdf-9da3-4b89-90fb-cdbbdfccebd2">

**Comment by ironmonk88** [comment]
Fixed in the latest release.
