### ISSUE TITLE
[BUG] Set flag error when combat starts

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk88/monks-bloodsplats#29]
When you click Begin Encounter on the combat tracker, this console error appears.
<img width="560" alt="Screenshot 2023-09-29 at 11 56 13 AM" src="https://github.com/ironmonk88/monks-bloodsplats/assets/90105219/6957cfd7-3e6b-4b1a-a619-6c2d565e6480">

Foundry v11 build 309, Pf2e 5.6.1

**Comment by ironmonk88** [comment]
Fixed in the latest release.
