### ISSUE TITLE
[BUG] Settings Typo

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#30]
![image](https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/f1f769b3-25eb-4e73-a403-5df0b2aafee8)

Bloodsplats 11.05

**Comment by ironmonk88** [comment]
Fixed in the latest version

**Comment by Crowguard** [comment]
![image](https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/417edb35-7488-49eb-a9b9-3486aba3f79b)
Seems to have unfixed itself at some point.

Foundry 11.315
Bloodsplats 11.12
