### ISSUE TITLE
[BUG] Cannot change blood colour

### ISSUE THREAD

**Issue by Scooby-Goober** [ironmonk88/monks-bloodsplats#31]
When I edit the setting "Edit Types: Choose which types of images and colours apply to tokens" and change the selected blood colour, the blood colour remains the default bright red.

![image](https://github.com/ironmonk88/monks-bloodsplats/assets/113794179/e68356f6-7a16-4200-8ec4-9a6e52097169)

**To Reproduce**
1. Go to: Setting / Monk's Bloodsplats
2. Click on: Edit Types
3. Change colour
4. Save changes in pop-out
5. Save changes in game settings + reload application
4. See error (i.e. change does not take effect) 

**Please complete as much of the following information as possible:**
 - Browser: Hosted on PC
 - Foundry Version: V11
 - System: WFRP by Mooman
 - Module version: 11.05
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes

**Comment by ironmonk88** [comment]
Fixed in the latest version
