### ISSUE TITLE
[BUG] Token Lock Stays on Outside of Combat

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#33]
The token lock feature is still applying outside of combat sometimes. 

Also, the lock can be bypassed with the lasso select. 

No errors.

https://github.com/ironmonk88/monks-bloodsplats/assets/99844555/886dcaa9-4011-47f4-b952-f476478a07ba

Foundry 11.315
Bloodsplats 11.09

**Comment by ironmonk88** [comment]
Fixed in the latest version.  At least I think it has.
